Inu 264 8 dress keychain wrapper
shakurocom/iOS_Toolbox pull request #1
Opened 2018-02-15 07:59 UTC by SanakaBarabaka

2018-08-03 10:49 UTC, vonipchenko requested changes

2018-08-03 10:49 UTC, vonipchenko commented on Keychain/README.md
> +KeychainWrapper work with `Codable` objects:
WORKS

2018-08-03 10:49 UTC, vonipchenko commented on Keychain/README.md
> +    let credentials = UserCredentials(username: "Vasya", password: "123")
Please replace "Vasya" with myUsername and  "123" with myPassword

2018-08-03 10:49 UTC, vonipchenko commented on Keychain/Source/KeychainWrapper.swift
> +        public init(serviceName: String, account: String, itemName: String? = nil, accessGroup: String? = nil, secValue: T) {
"Place parameters that don’t have default values at the beginning of a function’s parameter list, before the parameters that have default values. Parameters that don’t have default values are usually more important to the function’s meaning—writing them first makes it easier to recognize that the same function is being called, regardless of whether any default parameters are omitted."

2018-08-03 10:49 UTC, vonipchenko commented on Keychain/Source/KeychainWrapper.swift
> +    public static func saveKeychainItem<T>(_ item: KeychainWrapper.Item<T>) throws where T:Encodable {
missing whitespace T:Encodable
Please check via linter

2018-08-03 10:49 UTC, vonipchenko commented on Keychain/Source/KeychainWrapper.swift
> +    public struct Item<T> {
missing generic constraint to Encodable

2018-08-03 10:49 UTC, vonipchenko commented on Keychain/Source/KeychainWrapper.swift
> +            throw KeychainWrapper.Error.encodeSecValueError
Please do not hide JSONEncoder() original error.
I think there two options:
1) Just use try JSONEncoder().encode(item.secValue) to leave original error
2) Add associated value to the "encodeSecValueError" with original error from JSONEncoder

2018-08-06 12:42 UTC, SanakaBarabaka commented
add ability to get transform from preview layer of video camera - this is used with metadata output for correct frame transformation

2018-08-13 14:05 UTC, SanakaBarabaka commented on Keychain/Source/KeychainWrapper.swift
> +            throw KeychainWrapper.Error.encodeSecValueError
added TODO to private repo

2018-08-21 11:05 UTC, merged