Inu 264 17 dress video camera
shakurocom/iOS_Toolbox pull request #7
Opened 2018-02-20 12:29 UTC by SanakaBarabaka

2018-08-07 12:37 UTC, vonipchenko requested changes

2018-08-07 12:37 UTC, vonipchenko commented on VideoCamera/Source/SimulatorCamera.swift
> +            throw VideoCameraError.invalidConfiguration(message: "simulated image is not provided")
Do not trhow errror, please just provide default image

2018-08-13 14:21 UTC, SanakaBarabaka commented on VideoCamera/Source/SimulatorCamera.swift
> +            throw VideoCameraError.invalidConfiguration(message: "simulated image is not provided")
moved to TODO to private repo

2018-08-15 08:38 UTC, moseskimjj commented on README.md
> +- [Components List](#components-list)
Component List

2018-08-15 08:39 UTC, moseskimjj commented on README.md
> +## Components List
Component List

2018-08-15 08:44 UTC, moseskimjj commented on README.md
> +    - **DeviceType** - Helper for detecting model of the device / simulator.
A helper for detecting the model of the device/simulator.

2018-08-15 08:44 UTC, moseskimjj commented on README.md
> +    - **DeviceOrientationListener** - Alternative for UIDevice.current.orientation.
The alternative for UIDevice.current.orientation.

2018-08-15 08:45 UTC, moseskimjj commented on README.md
> +    - **ImageProcessor** - Helper for CGImage and UIImage
A helper for CGImage and UIImage.

2018-08-15 08:47 UTC, moseskimjj commented on README.md
> +    - **KeychainWrapper** - easy add/remove/get Codable object to/from Keychain.
A wrapper to easily add, remove, or get a Codable object to/from Keychain.

2018-08-15 08:47 UTC, moseskimjj commented on README.md
> +    - **KeyboardHandler** - wrapper around keyboard notifications
A wrapper around the keyboard notifications.

2018-08-15 08:48 UTC, moseskimjj commented on README.md
> +- [PlaceholderTextView](/PlaceholderTextView/) - UITextView subclass with a placeholder feature and ability to change own size depending on text contents
A UITextView subclass with a placeholder feature and the ability to change own size depending on the text contents.

2018-08-15 08:49 UTC, moseskimjj commented on README.md
> +- [VideoCamera](/VideoCamera/) - wrapper for AVFoundation's camera.
A wrapper for the AVFoundation camera.

2018-08-15 08:49 UTC, moseskimjj commented on README.md
> +[CocaPods](http://cocapods.org) is a dependency manager for Coca projects. You can install it with the following command:
is a dependency manager for the Coca projects.

2018-08-15 08:49 UTC, moseskimjj commented on README.md
> +To integrate Toolbox into you Xcode project, specify it in your `Podfile`:
To integrate Toolbox into your Xcode project, specify it in your `Podfile`:

2018-08-15 10:20 UTC, moseskimjj commented on README.md
> +If you prefer to not use CocoPods, than you can integrate any/all components from Shakuro iOS Toolbox simply by copying them to your project
If you prefer not to use CocoaPods, you can integrate any/all components from the Shakuro iOS Toolbox simply by copying them to your project.

2018-08-15 10:29 UTC, moseskimjj commented on README.md
> +You can use integrate only needed components. To do this you need to specify subpod:
You can use/integrate only the necessary components. To do this, you need to specify the subpod:

2018-08-21 11:05 UTC, merged